### ISSUE TITLE
import sciluigi failed

### ISSUE THREAD

**Issue by aboidriss** [pharmbio/sciluigi#58]
Hello,

When I execute :
 `import sciluigi as sl`
I get the following error : 

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    import sciluigi as sl
  File "/usr/local/lib/python3.6/site-packages/sciluigi/__init__.py", line 16, in <module>
    from sciluigi import interface
  File "/usr/local/lib/python3.6/site-packages/sciluigi/interface.py", line 52, in <module>
    setup_logging()
  File "/usr/local/lib/python3.6/site-packages/sciluigi/interface.py", line 45, in setup_logging
    luigi.interface.setup_interface_logging.has_run = True
AttributeError: module 'luigi.interface' has no attribute 'setup_interface_logging'

After looking into luigi's repo, I found that the function:
`setup_interface_logging` is deleted in the follwing commit : 

spotify/luigi@0a098f6f99da0bad03af56a057b9a15254d1a957

Any solution please ?

**Comment by FreddieSun** [comment]
same problem, any idea?
